// Minimal, offline Thunderbird profile used only by test-inbox.sh.
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account2.identities", "id2,id3");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.account.account3.identities", "id4,id5");
user_pref("mail.account.account3.server", "server3");
user_pref("mail.accountmanager.accounts", "account1,account2,account3");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.accountmanager.localfoldersserver", "server1");
user_pref("mail.identity.id1.fullName", "ThunderSub Tester");
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.useremail", "tester@thundersub.invalid");
user_pref("mail.identity.id2.fullName", "Personal Tester");
user_pref("mail.identity.id2.smtpServer", "smtp1");
user_pref("mail.identity.id2.useremail", "personal@thundersub.invalid");
user_pref("mail.identity.id3.fullName", "Shopping Alias");
user_pref("mail.identity.id3.smtpServer", "smtp1");
user_pref("mail.identity.id3.useremail", "shopping@thundersub.invalid");
user_pref("mail.identity.id4.fullName", "Work Tester");
user_pref("mail.identity.id4.smtpServer", "smtp1");
user_pref("mail.identity.id4.useremail", "work@thundersub.invalid");
user_pref("mail.identity.id5.fullName", "Newsletter Alias");
user_pref("mail.identity.id5.smtpServer", "smtp1");
user_pref("mail.identity.id5.useremail", "newsletters@thundersub.invalid");
user_pref("mail.server.server1.check_new_mail", false);
user_pref("mail.server.server1.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server1.download_on_biff", false);
user_pref("mail.server.server1.hostname", "Local Folders");
user_pref("mail.server.server1.login_at_startup", false);
user_pref("mail.server.server1.name", "ThunderSub Test Inbox");
user_pref("mail.server.server1.type", "none");
user_pref("mail.server.server1.userName", "nobody");
user_pref("mail.server.server2.check_new_mail", false);
user_pref("mail.server.server2.directory-rel", "[ProfD]Mail/Personal Inbox");
user_pref("mail.server.server2.download_on_biff", false);
user_pref("mail.server.server2.hostname", "personal.thundersub.invalid");
user_pref("mail.server.server2.login_at_startup", false);
user_pref("mail.server.server2.name", "Personal Inbox");
user_pref("mail.server.server2.type", "none");
user_pref("mail.server.server2.userName", "personal");
user_pref("mail.server.server3.check_new_mail", false);
user_pref("mail.server.server3.directory-rel", "[ProfD]Mail/Work Inbox");
user_pref("mail.server.server3.download_on_biff", false);
user_pref("mail.server.server3.hostname", "work.thundersub.invalid");
user_pref("mail.server.server3.login_at_startup", false);
user_pref("mail.server.server3.name", "Work Inbox");
user_pref("mail.server.server3.type", "none");
user_pref("mail.server.server3.userName", "work");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.hostname", "localhost.invalid");
user_pref("mail.smtpserver.smtp1.port", 1);
user_pref("mail.smtpserver.smtp1.username", "nobody");
user_pref("mail.smtpservers", "smtp1");
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.enabledScopes", 15);
user_pref("extensions.startupScanScopes", 15);
user_pref("xpinstall.signatures.required", false);
user_pref("mail.shell.checkDefaultClient", false);
user_pref("mailnews.start_page.enabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
